environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    ARCH: amd64
    BITS: 64
    CFG_DISABLE_CROSS_TESTS: 1
    MAKE_TARGETS: test-unit-x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
    ARCH: x86
    BITS: 32
    MINGW_URL: https://s3.amazonaws.com/rust-lang-ci
    MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    MINGW_DIR: mingw32
    CFG_DISABLE_CROSS_TESTS: 1
    MAKE_TARGETS: test-unit-i686-pc-windows-gnu
  - TARGET: i686-pc-windows-msvc
    BITS: 32
    ARCH: x86
    MAKE_TARGETS: test-unit-i686-pc-windows-msvc
    CFG_DISABLE_CROSS_TESTS: 1
  - TARGET: x86_64-pc-windows-msvc
    OTHER_TARGET: i686-pc-windows-msvc
    BITS: 64
    ARCH: amd64
    MAKE_TARGETS: test-unit-x86_64-pc-windows-msvc
install:
  - set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - if defined MINGW_URL appveyor DownloadFile %MINGW_URL%/%MINGW_ARCHIVE%
  - if defined MINGW_URL 7z x -y %MINGW_ARCHIVE% > nul
  - if defined MINGW_URL set PATH=%CD%\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%
  - if defined OTHER_TARGET rustup target add %OTHER_TARGET%
  - rustc -V
  - cargo -V
  - git submodule update --init  
build: false
test_script:
  - cargo test
  - cargo test --no-default-features
  - cargo run
