(function() {var implementors = {};
implementors["craft"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/dependency/enum.Kind.html' title='craft::dependency::Kind'>Kind</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/ops/enum.CompileMode.html' title='craft::ops::CompileMode'>CompileMode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/ops/enum.MessageFormat.html' title='craft::ops::MessageFormat'>MessageFormat</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/ops/enum.VersionControl.html' title='craft::ops::VersionControl'>VersionControl</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='craft/ops/struct.Unit.html' title='craft::ops::Unit'>Unit</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/ops/enum.Kind.html' title='craft::ops::Kind'>Kind</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/resolver/enum.Method.html' title='craft::resolver::Method'>Method</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/shell/enum.Verbosity.html' title='craft::shell::Verbosity'>Verbosity</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/shell/enum.ColorConfig.html' title='craft::shell::ColorConfig'>ColorConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='craft/shell/struct.ShellConfig.html' title='craft::shell::ShellConfig'>ShellConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/util/config/enum.Location.html' title='craft::util::config::Location'>Location</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='craft/util/enum.Freshness.html' title='craft::util::Freshness'>Freshness</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
